// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubcxlwouxklavvksinek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InViY3hsd291eGtsYXZ2a3NpbmVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDAzMjUsImV4cCI6MjA2NzExNjMyNX0.2nzA7TIIGgpGb5_ir_TUFACHd_mQHcqG-c-Hrq-lnxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});